---
#
#  Some cloud providers do not provide an adequate swapfile allocation when
#  they create an instance.  This set of processes allocates a swapfile if
#  needed and ensures
- name: Create a Swap File
  shell:
    cmd: |
      set -e
      [ -f /swapfile ] && exit 1
      fallocate -l 2g /swapfile
      mkswap /swapfile
  become: yes
  register: sh1
  failed_when: sh1.rc > 1
  changed_when: sh1.rc == 0

- name: Activate the Swap File
  shell:
    executable: /bin/bash
    cmd: |
      set -euo pipefail
      grep '^/swapfile$' <(swapon --noheadings --show=name) && exit 1
      swapon /swapfile
  become: yes
  register: sh2
  failed_when: sh2.rc > 1
  changed_when: sh2.rc == 0

- name: Add the swapfile line to the fstab table for restarts
  lineinfile:
    #  Don't bork any existing swapfile line
    #   TODO: I'm not sure the regex is correct :(
    path: /etc/fstab
    regex: '^[^#]/swapfile\s.*\sswap\s'
    line: /swapfile none swap sw 0 0
  become: yes
