---
- name: Pip install the docker module (needed for docker_login)
  pip:
    name: docker
    state: present
  become: yes

- name: Configure available users for docker
  include_tasks: user.yml
  vars:
    user: "{{ docker_slave_user }}"
  loop:
    - demo
    - jenkins_slave
  loop_control:
    loop_var: docker_slave_user
