- name: Add apt signing key for Bazel repository
  apt_key:
    id: 3D5919B448457EE0
    url: https://bazel.build/bazel-release.pub.gpg
    state: present
  become: yes

- name: Add Bazel apt repository to sources
  apt_repository:
    repo: 'deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8'
    state: present
    filename: bazel
  become: yes

- name: Install Bazel packages
  apt:
    update_cache: yes
    name: bazel
    state: present
    install_recommends: no
  become: yes
