---
#
#  Create Jenkins build slave nodes.  This playbook does not actually
#  configure Jenkins with the nodes, but at the end, that configuration
#  should be fairly straightforward -- add the node; retrieve the host key.
#
- hosts: podman_slaves
  any_errors_fatal: true
  roles:
    - role: podman_slave
