---
#
#  Add the Docker Ubuntu repository to the system, update the caches, and
#  install docker.
#
- name: Install docker on Ubuntu
  import_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  become: yes

- name: Install docker on Fedora
  import_tasks: fedora.yml
  when: ansible_distribution == "Fedora"
  become: yes
