---
- name: Add apt signing key for Docker repository
  apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker apt repository to sources
  apt_repository:
    repo: 'deb [arch={{ repository_arch[ansible_machine] }}]
        https://download.docker.com/linux/ubuntu
        {{ ansible_distribution_release }} stable'
    state: present
    filename: docker

- name: Install Docker packages
  apt:
    update_cache: yes
    name:
    - docker-ce
    - jq
    state: present
    install_recommends: no
  register: docker_install

#
#  Some packages have not been broken out on some architectures, so we will
#  test the cache list to determine whether they exist.
#
- name: Test for docker-ce-cli and containerd.io packages
  shell: apt-cache show {{ item }}
  register: new_docker
  loop:
    - docker-ce-cli
    - containerd.io
  changed_when: False
  failed_when: (new_docker.rc != 0) and (new_docker.rc != 100)

#
#  Use the results of the prior step to request or confirm install of CLI and
#  containerd.io.
#
- name: Install Docker CLI and Containerd packages
  apt:
    name: '{{ new_docker.results | selectattr("rc","eq","0")
              | map(attribute="item") | list }}'
    state: present
    install_recommends: no
  register: docker_extras_install

- name: Restart Docker service
  service:
    name: docker
    state: restarted
  become: yes
  when: docker_install.changed or docker_extras_install.changed
